# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RRIM
                                 A QGIS plugin
 Genera RRIM a partir de datos de elevación
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-05
        copyright            : (C) 2020 by David Ríos Santana
        email                : davriosan@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'David Ríos Santana'
__date__ = '2020-05-05'
__copyright__ = '(C) 2020 by David Ríos Santana'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RRIM class from file RRIM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rrim import RRIMPlugin
    return RRIMPlugin(iface)
