# -*- coding: utf-8 -*-

"""
/***************************************************************************
 RRIM
                                 A QGIS plugin
 Genera RRIM a partir de datos de elevación
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-05
        copyright            : (C) 2020 by David Ríos Santana
        email                : davriosan@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'David Ríos Santana'
__date__ = '2020-05-05'
__copyright__ = '(C) 2020 by David Ríos Santana'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon

from qgis.core import QgsProcessingAlgorithm, QgsApplication
import processing
from .rrim_provider import RRIMProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class RRIMPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = RRIMProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        # Cadena para crear un acceso directo en el menú de complementos, junto con su grupo, subgrupo
        # e icono. Se definen los nombres que se quieren que aparezcan.
        icon = os.path.join(os.path.join(cmd_folder, 'logo.png'))
        self.action = QAction(
            QIcon(icon),
            u"Red Relief Image Map generator", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu(u"RRIM", self.action)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        # Código para eliminar el complemento del menú en caso de ser desinstalado.
        QgsApplication.processingRegistry().removeProvider(self.provider)
        self.iface.removePluginMenu(u"&RRIM", self.action)
        self.iface.removeToolBarIcon(self.action)
        
    def run(self):
        #Se conecta el botón del menú con el acceso en la barra de herramientas.
        processing.execAlgorithmDialog("RRIM:Red Relief Image Map generator")